// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIP() {
  return window['go']['main']['App']['GetIP']();
}

export function GetIPs() {
  return window['go']['main']['App']['GetIPs']();
}
