// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIPs() {
  return window['go']['main']['App']['GetIPs']();
}

export function GetMaybeLocalIP() {
  return window['go']['main']['App']['GetMaybeLocalIP']();
}

export function OpenCacheDir() {
  return window['go']['main']['App']['OpenCacheDir']();
}
