// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIP():Promise<string>;

export function GetIPs():Promise<Array<string>>;
